name: Build and push docker image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (cpp)
        uses: docker/build-push-action@v2
        with:
          context: ./cpp
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-cpp:latest

      - name: Build and push (cpp17)
        uses: docker/build-push-action@v2
        with:
          context: ./cpp
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-cpp17:latest

      - name: Build and push (cpp-with-libs)
        uses: docker/build-push-action@v2
        with:
          context: ./cpp-with-libs
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-cpp-with-libs:latest

      - name: Build and push (python)
        uses: docker/build-push-action@v2
        with:
          context: ./python
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-python:latest
