name: Build and push docker image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (cpp)
        uses: docker/build-push-action@v2
        with:
          context: ./cpp
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-cpp:latest

      - name: Build and push (python)
        uses: docker/build-push-action@v2
        with:
          context: ./python
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-python:latest

      - name: Build and push (rust)
        uses: docker/build-push-action@v2
        with:
          context: ./rust
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-rust:latest

      - name: Build and push (rust-ahc)
        uses: docker/build-push-action@v2
        with:
          context: ./rust-ahc
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-rust-ahc:latest

      - name: Build and push (ac-cli)
        uses: docker/build-push-action@v2
        with:
          context: ./ac-cli
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 17cl/atcoder-ac-cli:latest
